# Generated by Django 4.2.3 on 2023-07-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MachineryInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название техники"
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (1, "Tractor"),
                            (2, "Combine Harvester"),
                            (3, "Equipment Sowing"),
                            (4, "Plow"),
                            (5, "Mowing Grass"),
                            (6, "Sprayer"),
                            (7, "Trailer"),
                            (8, "Dump Truck"),
                            (9, "Lift Truck"),
                        ],
                        verbose_name="Категория техники",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание техники"),
                ),
                (
                    "attachments_available",
                    models.BooleanField(
                        verbose_name="Возможность навесного оборудования"
                    ),
                ),
                (
                    "power_hp",
                    models.PositiveSmallIntegerField(
                        verbose_name="Мощность, л.с."
                    ),
                ),
                (
                    "payload_capacity_kg",
                    models.PositiveSmallIntegerField(
                        verbose_name="Грузоподъемность, кг"
                    ),
                ),
            ],
            options={
                "verbose_name": "Техника",
                "verbose_name_plural": "Техники",
            },
        ),
        migrations.CreateModel(
            name="Machinery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_of_manufacture",
                    models.PositiveSmallIntegerField(
                        verbose_name="Год выпуска"
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True, verbose_name="Доступность"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=100, verbose_name="Местонахождение"
                    ),
                ),
                (
                    "mileage",
                    models.PositiveSmallIntegerField(verbose_name="Пробег"),
                ),
                (
                    "delivery_distance_km",
                    models.PositiveSmallIntegerField(
                        verbose_name="Дистанция доставки, км"
                    ),
                ),
                (
                    "delivery_cost",
                    models.PositiveIntegerField(
                        verbose_name="Стоимость доставки"
                    ),
                ),
                (
                    "rental_price",
                    models.PositiveIntegerField(
                        verbose_name="Стоимость аренды"
                    ),
                ),
                (
                    "machinery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machineries",
                        to="machineries.machineryinfo",
                        verbose_name="Техника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка техники",
                "verbose_name_plural": "Карточки техники",
            },
        ),
    ]
