# Generated by Django 4.2.3 on 2023-07-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machineries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machineryinfo",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "Tractors"),
                    (2, "Combines"),
                    (3, "Equipment Sowing"),
                    (4, "Motorized Tractors"),
                    (5, "Trailers"),
                    (6, "Plows"),
                    (7, "Lift Trucks"),
                    (8, "Attachments"),
                ],
                verbose_name="Категория техники",
            ),
        ),
    ]
