# Generated by Django 4.2.3 on 2023-08-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("machineries", "0003_favorite_favorite_double_favorite_unique_"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="machinery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="machineries.machinery",
                verbose_name="Техника",
            ),
        ),
    ]
