# Generated by Django 4.2.3 on 2023-08-09 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("machineries", "0004_alter_favorite_machinery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machineryinfo",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "Трактора"),
                    (2, "Комбайны"),
                    (3, "Посевная техника"),
                    (4, "Мототракторы"),
                    (5, "Прицепы"),
                    (6, "Плуги"),
                    (7, "Погрузчики"),
                    (8, "Навесное оборудование"),
                ],
                verbose_name="Категория техники",
            ),
        ),
        migrations.CreateModel(
            name="ImageMachinery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_image",
                    models.CharField(blank=True, max_length=100),
                ),
                ("image", models.ImageField(upload_to="machinery_image/")),
                ("main_image", models.BooleanField(default=False)),
                (
                    "machinery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machineries.machineryinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
                "default_related_name": "images_machinery",
            },
        ),
    ]
