# Generated by Django 4.2.3 on 2023-08-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("machineries", "0005_alter_machineryinfo_category_imagemachinery"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineryBrandname",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        max_length=100, verbose_name="Марка техники"
                    ),
                ),
            ],
            options={
                "verbose_name": "Марка техники",
                "verbose_name_plural": "Марки техники",
            },
        ),
        migrations.AlterModelOptions(
            name="machineryinfo",
            options={
                "verbose_name": "Модель техники",
                "verbose_name_plural": "Модели техники",
            },
        ),
        migrations.AlterField(
            model_name="machineryinfo",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Модель техники"
            ),
        ),
        migrations.AddField(
            model_name="machineryinfo",
            name="mark",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brandname",
                to="machineries.machinerybrandname",
                verbose_name="Марка техники",
            ),
            preserve_default=False,
        ),
    ]
