# Generated by Django 4.2.4 on 2023-08-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machineries", "0007_alter_imagemachinery_machinery"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
            ],
            options={
                "verbose_name": "Вид работ",
                "verbose_name_plural": "Виды работ",
            },
        ),
        migrations.AddField(
            model_name="machineryinfo",
            name="work_type",
            field=models.ManyToManyField(
                related_name="machinery_info",
                to="machineries.worktype",
                verbose_name="тип работ",
            ),
        ),
    ]
