# Generated by Django 4.2.4 on 2023-08-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machineries", "0008_worktype_machineryinfo_work_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machinerybrandname",
            options={
                "ordering": ["brand"],
                "verbose_name": "Марка техники",
                "verbose_name_plural": "Марки техники",
            },
        ),
        migrations.RemoveField(
            model_name="machinery",
            name="delivery_cost",
        ),
        migrations.RemoveField(
            model_name="machinery",
            name="rental_price",
        ),
        migrations.AddField(
            model_name="machinery",
            name="price_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=7,
                verbose_name="Стоимость аренды в час",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machinery",
            name="price_per_shift",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Стоимость аренды за смену",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machinerybrandname",
            name="country_of_origin",
            field=models.CharField(
                default="Россия",
                max_length=100,
                verbose_name="Страна-производитель",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="machineryinfo",
            name="attachments_available",
            field=models.BooleanField(
                default=False,
                verbose_name="Возможность навесного оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="machineryinfo",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="machineryinfo",
            name="work_type",
            field=models.ManyToManyField(
                related_name="machinery_info",
                to="machineries.worktype",
                verbose_name="Тип работ",
            ),
        ),
    ]
