# Generated by Django 4.2.4 on 2023-08-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machineries", "0009_alter_machinerybrandname_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinery",
            name="price_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=7,
                verbose_name="Цена аренды в час",
            ),
        ),
        migrations.AlterField(
            model_name="machinery",
            name="price_per_shift",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                verbose_name="Цена аренды за смену",
            ),
        ),
    ]
