# Generated by Django 4.2.4 on 2023-08-31 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("machineries", "0010_alter_machinery_price_per_hour_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machinery",
            options={
                "default_related_name": "machineries",
                "verbose_name": "Карточка техники",
                "verbose_name_plural": "Карточки техники",
            },
        ),
        migrations.AlterField(
            model_name="machinery",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.location",
                verbose_name="Местонахождение",
            ),
        ),
        migrations.AlterField(
            model_name="machinery",
            name="machinery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="machineries.machineryinfo",
                verbose_name="Техника",
            ),
        ),
    ]
