# Generated by Django 4.2.3 on 2023-09-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machineries", "0010_alter_machinery_price_per_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinery",
            name="count_orders",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество заказов"
            ),
        ),
    ]
