repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace # Убирает лишние пробелы
    - id: end-of-file-fixer # Добавляет пустую строку в конце файла
    - id: check-yaml # Проверяет синтаксис .yaml файлов
    - id: check-added-large-files # Проверяет, не добавляются ли большие файлы.
      args: ['--maxkb=300']  # максимальный размер добавляемого файла 300 кБ
    - id: check-merge-conflict # Проверяет, нет ли файлов, содержащих конфликтующие строки слияния.

# Линтер black
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3.10
      args:
        - --line-length=79
        - --include=src/

# Проверяет есть ли изменения в моделях не зафиксированные в миграциях
-   repo: local
    hooks:
    - id: pre-commit-check-makemigrations
      name: Check django migrations
      entry: ./src/manage.py makemigrations --check --dry-run
      language: system
      types: [python]
      pass_filenames: false
