# Generated by Django 4.2.3 on 2023-07-31 11:31

import core.enums
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=15,
                region=None,
                verbose_name="Номер телефона",
            ),
        ),
    ]
