# Generated by Django 4.2.3 on 2023-08-01 07:41

import core.enums
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Callback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region=None,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=core.enums.Limits["MAX_LENGTH_COMMENT"],
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "is_finished",
                    models.BooleanField(
                        default=False, verbose_name="Завершено"
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "time_finished",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата завершения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Обратный звонок",
                "verbose_name_plural": "Обратные звонки",
                "default_related_name": "callback",
            },
        ),
    ]
