# Generated by Django 4.2.3 on 2023-08-07 11:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_callback_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=15,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
