# Generated by Django 4.2.3 on 2023-08-09 10:34

import core.enums
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название организации"
                    ),
                ),
                (
                    "inn",
                    users.models.NumericField(
                        max_length=12,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                core.enums.Limits["LENGTH_INN"]
                            )
                        ],
                        verbose_name="ИНН организации",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="users.organization",
                verbose_name="Организация",
            ),
        ),
    ]
