# Generated by Django 4.2.3 on 2023-08-09 17:44

import core.enums
import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_organization_user_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organization",
        ),
        migrations.AddField(
            model_name="user",
            name="inn",
            field=users.models.NumericField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        core.enums.Limits["LENGTH_INN"]
                    )
                ],
                verbose_name="ИНН организации",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Название организации",
            ),
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
    ]
