# Generated by Django 4.2.3 on 2023-08-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_user_organization_user_inn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата рождения"
            ),
        ),
    ]
