# Generated by Django 4.2.4 on 2023-08-31 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Субъект Федерации",
                "verbose_name_plural": "Субъекты Федерации",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, verbose_name="Наименование"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="locations.region",
                        verbose_name="Субъект Федерации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Населенный пункт",
                "verbose_name_plural": "Населенные пункты",
            },
        ),
    ]
