# Generated by Django 4.2.3 on 2023-08-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("machineries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Confirmed"),
                            (2, "Cancelled"),
                            (3, "At Work"),
                            (4, "Finished"),
                        ],
                        default=0,
                        verbose_name="Статус резервирования",
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения статуса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус резервирования",
                "verbose_name_plural": "Статусы резервирований",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        verbose_name="Дата начала резервирования"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        verbose_name="Дата окончания резервирования"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Комментарий к резервированию",
                    ),
                ),
                (
                    "machinery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="machineries.machinery",
                        verbose_name="Техника",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Резервирование",),
                "verbose_name_plural": "Резервирования",
            },
        ),
    ]
