# Generated by Django 4.2.3 on 2023-07-22 11:19

import core.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("machineries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Status Valid"), (1, "Status Cancelled")],
                        null=True,
                        verbose_name="Статус резервирования",
                    ),
                ),
                (
                    "date_from",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания резервирования",
                    ),
                ),
                (
                    "date_to",
                    models.DateTimeField(
                        verbose_name="Дата окончания срока резервирования"
                    ),
                ),
                (
                    "machinery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="machineries.machineryinfo",
                        verbose_name="Техника",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_renters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Арендодатель",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_tenants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Арендатор",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Резервирование",),
                "verbose_name_plural": "Резервирования",
                "ordering": ("date_from",),
            },
        ),
        migrations.CreateModel(
            name="ReservationList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=core.enums.Limits["DEFAULT_QUANTITY"],
                        verbose_name="Количество единиц",
                    ),
                ),
                (
                    "reservation",
                    models.ManyToManyField(
                        related_name="reservation_lists",
                        to="orders.reservation",
                        verbose_name="Резервирование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент резервирования",
                "verbose_name_plural": "Элементы резервирования",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.BooleanField(
                        default=False, verbose_name="Статус оплаты"
                    ),
                ),
                (
                    "order_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "At Work"), (1, "Finished")],
                        null=True,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "date_from",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания заказа"
                    ),
                ),
                (
                    "date_to",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата исполнения заказа"
                    ),
                ),
                (
                    "reservation_list",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orders.reservationlist",
                        verbose_name="Резервирование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ("date_from",),
            },
        ),
    ]
