# Generated by Django 4.2.3 on 2023-07-31 13:38

import core.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("machineries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Created"),
                            (1, "Confirmed"),
                            (2, "Cancelled By Client"),
                            (3, "Cancelled By Manager"),
                            (4, "At Work"),
                            (5, "Finished"),
                        ],
                        null=True,
                        verbose_name="Статус резервирования",
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения статуса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус резервирования",
                "verbose_name_plural": "Статусы резервирований",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        verbose_name="Дата начала резервирования"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        verbose_name="Дата окончания резервирования"
                    ),
                ),
                (
                    "is_need_attachment",
                    models.BooleanField(
                        default=False, verbose_name="Навесное оборудование"
                    ),
                ),
                (
                    "is_need_driver",
                    models.BooleanField(
                        default=False, verbose_name="Водитель техники"
                    ),
                ),
                (
                    "is_need_delivery",
                    models.BooleanField(
                        default=False, verbose_name="Доставка техники"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=core.enums.Limits[
                            "RESERVATION_COMMENT_MAX_LENGTH"
                        ],
                        null=True,
                        verbose_name="Комментарий к резервированию",
                    ),
                ),
                (
                    "machinery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="machineries.machinery",
                        verbose_name="Техника",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Арендатор",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="orders.reservationstatus",
                        verbose_name="Статус резервирования",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Резервирование",),
                "verbose_name_plural": "Резервирования",
            },
        ),
    ]
