# Generated by Django 4.2.4 on 2023-08-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Confirmed"),
                            (2, "Cancelled"),
                            (3, "At Work"),
                            (4, "Finished"),
                        ],
                        default=0,
                        verbose_name="Статус резервирования",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=150, verbose_name="Описание статуса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус резервирования",
                "verbose_name_plural": "Статусы резервирований",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "verbose_name": "Резервирование",
                "verbose_name_plural": "Резервирования",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationstatus",
            options={
                "verbose_name": "Статус Заказа",
                "verbose_name_plural": "Статусы заказов",
            },
        ),
        migrations.RemoveField(
            model_name="reservationstatus",
            name="name",
        ),
        migrations.AddField(
            model_name="reservation",
            name="number",
            field=models.CharField(
                default="1", max_length=30, verbose_name="Номер заказа"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservationstatus",
            name="reservation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.reservation",
                verbose_name="Заказ",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end_date",
            field=models.DateTimeField(
                verbose_name="Время окончания резервирования"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_date",
            field=models.DateTimeField(
                verbose_name="Время начала резервирования"
            ),
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
        migrations.AddField(
            model_name="reservationstatus",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.status",
                verbose_name="Статус заказа.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.ManyToManyField(
                related_name="reservations",
                through="orders.ReservationStatus",
                to="orders.status",
                verbose_name="Статусы резервирования",
            ),
        ),
    ]
