# Generated by Django 4.2.3 on 2023-08-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_status_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
        migrations.DeleteModel(
            name="ReservationStatus",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Created"),
                    (1, "Confirmed"),
                    (2, "Cancelled"),
                    (3, "At Work"),
                    (4, "Finished"),
                ],
                default=0,
                verbose_name="Статусы резервирования",
            ),
        ),
    ]
