# Generated by Django 4.2.3 on 2023-08-18 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_status_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationstatus",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_status",
                to="orders.reservation",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="reservationstatus",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.status",
                verbose_name="Статус заказа",
            ),
        ),
    ]
