# Generated by Django 4.2.3 on 2023-08-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0003_remove_reservation_status_delete_reservationstatus_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Создан"),
                    (1, "Подтвержден"),
                    (2, "Отменен"),
                    (3, "В работе"),
                    (4, "Завершен"),
                ],
                default=0,
                verbose_name="Статусы резервирования",
            ),
        ),
    ]
