# Generated by Django 4.2.3 on 2023-09-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0004_reservation_created_at_reservation_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="number",
            field=models.CharField(
                max_length=12, unique=True, verbose_name="Номер заказа"
            ),
        ),
    ]
