# Generated by Django 4.2.4 on 2023-09-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_reservation_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=9,
                verbose_name="Стоимость аренды",
            ),
            preserve_default=False,
        ),
    ]
