from enum import IntEnum


class Limits(IntEnum):
    MAX_LENGTH_FIRST_NAME = 50
    MAX_LENGTH_LAST_NAME = 50
    MAX_LENGTH_PATRONYMIC = 50
    MAX_LENGTH_PHONE_NUMBER = 15
    MAX_LENGTH_COMMENT = 250
    RESERVATION_COMMENT_MAX_LENGTH = 1000
    MAX_LENGTH_NAME_ORGANIZATION = 100
    LENGTH_INN = 12
    MIN_LENGTH_PASS = 8
    MAX_LENGTH_PASS = 25
