from enum import IntEnum


class Limits(IntEnum):
    MAX_LENGTH_FIRST_NAME = 50
    MAX_LENGTH_LAST_NAME = 50
    MAX_LENGTH_PATRONYMIC = 50
    MAX_LENGTH_PHONE_NUMBER = 15
    MAX_LENGTH_COMMENT = 250
