name: Build and deploy to production
on:
  pull_request:
    types: closed
    branches:
      - main
jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Generate .env
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          envkey_CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          envkey_DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          envkey_FRONTEND_DOCKERHUB_USERNAME: ${{ secrets.FRONTEND_DOCKERHUB_USERNAME }}
          envkey_EMAIL_FILE: ${{ secrets.EMAIL_FILE }}
          envkey_EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          envkey_EMAIL_USE_TLS: "YES"
          envkey_EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          envkey_EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          envkey_EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          envkey_TRANSFER: ${{ secrets.TRANSFER }}
          envkey_TRANSFER_SERVER: ${{ secrets.TRANSFER_SERVER }}
          envkey_TRANSFER_TOKEN: ${{ secrets.TRANSFER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          build-args: ENV_FILE=.env
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/amr:latest
      - name: Copy .env file to server using SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_LOGIN }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: ".env"
          target: ${{ secrets.TARGET_SERVER_PATH }}

  deploy:
    name: Deploy from image in Docker Hub
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_LOGIN }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.TARGET_SERVER_PATH }}
            docker-compose exec backend python3 manage.py dumpdata --indent 2 --exclude admin.logentry --exclude sessions.session > dump_$(date +%Y%m%d_%H%M).json
            docker-compose stop
            docker-compose rm -f backend
            docker rmi $(docker images '${{ secrets.DOCKER_HUB_USERNAME }}/amr' -q)
            docker-compose up -d
            docker-compose exec backend python manage.py migrate
            docker-compose exec backend python manage.py runcrons
